import type { ImageStyle, TextStyle, ViewStyle } from 'react-native';
import type { AppColors } from '../../theme/palette';
import { uiMetrics } from '../../theme/ui-metrics';
import type { WorldTheme } from '../../theme/world';

export function makeAccountSettingsStyles(palette: AppColors, world: WorldTheme, hairlineWidth = 1) {
  return {
  // No background: the sky backdrop shows through.
  content: { gap: 14, paddingHorizontal: uiMetrics.pageInset, paddingTop: 4 },
  profile: { flexDirection: 'row', alignItems: 'flex-start', flexWrap: 'wrap', gap: 14, backgroundColor: world.card, borderRadius: world.radius.card },
  profileCopy: { flex: 1, minWidth: 176, gap: 6 },
  profileBadge: { width: 64, height: 64 } as ImageStyle,
  title: { color: world.cardInk, fontSize: 22, lineHeight: 30, fontWeight: '800', letterSpacing: -0.3 },
  intro: { color: world.cardMuted, fontSize: 14, lineHeight: 21 },
  accountDiagnostic: { color: world.cardMuted, fontSize: 12, lineHeight: 18 },
  sessionActions: { alignSelf: 'stretch', gap: 10, paddingTop: 4 },
  sessionButtonHost: { minHeight: uiMetrics.minTouch },
  groupCard: { gap: 8, backgroundColor: world.card, borderRadius: world.radius.card },
  soundRow: { flexDirection: 'row', alignItems: 'center', gap: 12, minHeight: uiMetrics.minTouch },
  soundCopy: { flex: 1, gap: 4 },
  soundPanel: { gap: 14 },
  soundControlBlock: { gap: 8, paddingTop: 6, borderTopWidth: hairlineWidth, borderTopColor: palette.separator },
  soundControlHeader: { flexDirection: 'row', alignItems: 'center', gap: 12, minHeight: uiMetrics.minTouch },
  volumeTrack: { height: 22, borderRadius: 11, backgroundColor: palette.separator, overflow: 'hidden', justifyContent: 'center' },
  volumeFill: { position: 'absolute', left: 0, top: 0, bottom: 0, backgroundColor: palette.primary },
  volumeThumb: { width: 18, height: 18, borderRadius: 9, backgroundColor: palette.surface, borderWidth: 2, borderColor: palette.primary },
  volumeLabels: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  volumeText: { color: world.cardMuted, fontSize: 12, lineHeight: 18 },
  segmentRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  segmentButton: { minHeight: uiMetrics.minTouch, flexGrow: 1, flexBasis: 88, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 10, paddingVertical: 8, borderRadius: 12, borderWidth: 1, borderColor: palette.separator },
  segmentButtonActive: { borderColor: palette.primary, backgroundColor: palette.primaryContainer },
  segmentText: { color: world.cardMuted, fontSize: 13, fontWeight: '800' },
  segmentTextActive: { color: palette.onPrimaryContainer },
  sectionTitle: { color: world.cardInk, fontSize: 18, fontWeight: '800' },
  secondaryLink: { minHeight: uiMetrics.minTouch, alignSelf: 'flex-start', justifyContent: 'center', paddingHorizontal: 14, borderRadius: 14, borderWidth: 1, borderColor: palette.primary },
  secondaryLinkText: { color: palette.primary, fontSize: 14, fontWeight: '800' },
  card: { gap: 7, paddingVertical: 14, borderTopWidth: hairlineWidth, borderTopColor: palette.separator },
  cardTitle: { color: world.cardInk, fontSize: 16, fontWeight: '900' },
  cardBody: { color: world.cardMuted, fontSize: 14, lineHeight: 22 },
  statusCard: { gap: 7, padding: 18, borderRadius: world.radius.card, backgroundColor: palette.primaryContainer },
  statusTitle: { color: palette.onPrimaryContainer, fontSize: 16, fontWeight: '900' },
  statusBody: { color: palette.onPrimaryContainer, fontSize: 13, lineHeight: 20 },
  inputLabel: { color: world.cardInk, fontSize: 14, fontWeight: '900' },
  input: { minHeight: uiMetrics.minTouch, paddingHorizontal: 14, paddingVertical: 10, borderRadius: 14, borderWidth: 1.5, borderColor: world.cardMuted, color: palette.label, backgroundColor: palette.background, fontSize: 16 },
  receiptCode: { color: palette.onPrimaryContainer, fontSize: 22, lineHeight: 30, fontWeight: '900', letterSpacing: 1.5 },
  error: { padding: 14, borderRadius: 14, color: palette.onErrorContainer, backgroundColor: palette.errorContainer, lineHeight: 20 },
  message: { padding: 14, borderRadius: 14, color: palette.onPrimaryContainer, backgroundColor: palette.primaryContainer, lineHeight: 20 },
  liveRegion: { gap: 10 },
  deleteButton: { minHeight: 52, alignItems: 'center', justifyContent: 'center', borderRadius: 16, backgroundColor: palette.errorContainer },
  deleteButtonText: { color: palette.onErrorContainer, fontSize: 15, fontWeight: '900' },
  disabled: { opacity: 0.45 },
  note: { color: world.skyMuted, fontSize: 12, lineHeight: 19 },
  blockedCard: { gap: 8, padding: 18, borderRadius: world.radius.card, backgroundColor: palette.errorContainer },
  blockedTitle: { color: palette.onErrorContainer, fontSize: 15, fontWeight: '900' },
  blockedBody: { color: palette.onErrorContainer, fontSize: 13, lineHeight: 21 },
  } satisfies Record<string, ImageStyle | TextStyle | ViewStyle>;
}
