import type { ImageStyle, TextStyle, ViewStyle } from 'react-native';
import type { AppColors } from '../../theme/palette';
import type { WorldTheme } from '../../theme/world';

export function makeMerchantDetailStyles(palette: AppColors, world: WorldTheme, hairlineWidth = 1) {
  return {
  // Transparent on purpose: the sky illustration shows through, or the showcase picture is laid over it.
  banner: { height: 240, justifyContent: 'flex-end', padding: 12 },
  bannerArt: { position: 'absolute', top: 0, left: 0 } as ImageStyle,
  bannerNote: { alignSelf: 'flex-start', paddingHorizontal: 10, paddingVertical: 5, borderRadius: world.radius.chip, backgroundColor: world.card },
  bannerNoteText: { color: world.cardMuted, fontSize: 11, fontWeight: '700' },
  content: { gap: 16, paddingHorizontal: 20 },
  hero: { gap: 10, padding: 22, borderRadius: world.radius.card, backgroundColor: world.card },
  heroTopline: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  heroEyebrow: { color: palette.primary, fontSize: 11, fontWeight: '900', letterSpacing: 1.1 },
  demoBadge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: world.radius.chip, overflow: 'hidden', backgroundColor: palette.primaryContainer, color: palette.onPrimaryContainer, fontSize: 10, fontWeight: '900' },
  title: { color: world.cardInk, fontSize: 30, fontWeight: '900', lineHeight: 38, letterSpacing: -0.6 },
  story: { color: world.cardMuted, fontSize: 16, lineHeight: 25 },
  inlineError: { padding: 12, borderRadius: 12, backgroundColor: palette.errorContainer },
  inlineErrorText: { color: palette.onErrorContainer, fontSize: 13, lineHeight: 19 },
  infoCard: { paddingHorizontal: 18, paddingVertical: 6, borderRadius: world.radius.card, backgroundColor: world.card },
  infoRow: { flexDirection: 'row', gap: 18, paddingVertical: 16, borderBottomWidth: hairlineWidth, borderBottomColor: palette.separator },
  infoLabel: { width: 72, color: world.cardMuted, fontSize: 13, fontWeight: '700' },
  infoValue: { flex: 1, color: world.cardInk, fontSize: 14, fontWeight: '700', textAlign: 'right' },
  sectionEyebrow: { color: palette.primary, fontSize: 13, fontWeight: '900' },
  menuHeading: { marginTop: 12 },
  campaignTitle: { color: world.cardInk, fontSize: 24, fontWeight: '900', letterSpacing: -0.5 },
  period: { color: world.cardMuted, fontSize: 13 },
  rewardCard: { gap: 8, padding: 20, borderRadius: world.radius.card, backgroundColor: world.card },
  rewardHeading: { color: world.cardInk, fontSize: 18, fontWeight: '900' },
  rewardNote: { color: world.cardMuted, fontSize: 13, lineHeight: 20 },
  goalList: { marginTop: 10 },
  goalRow: { minHeight: 76, flexDirection: 'row', gap: 14 },
  timeline: { width: 34, alignItems: 'center' },
  goalNumber: { width: 32, height: 32, alignItems: 'center', justifyContent: 'center', borderRadius: 16, backgroundColor: palette.primaryContainer },
  goalNumberText: { color: palette.onPrimaryContainer, fontSize: 13, fontWeight: '900' },
  timelineLine: { flex: 1, width: 2, marginVertical: 5, backgroundColor: palette.separator },
  goalCopy: { gap: 3, paddingTop: 4 },
  goalLabel: { color: world.cardMuted, fontSize: 12, fontWeight: '700' },
  goalName: { color: world.cardInk, fontSize: 17, fontWeight: '800' },
  boundaryCard: { gap: 10, padding: 20, borderRadius: world.radius.card, backgroundColor: palette.primaryContainer },
  boundaryTitle: { color: palette.onPrimaryContainer, fontSize: 18, fontWeight: '900' },
  boundaryBody: { color: palette.onPrimaryContainer, fontSize: 14, lineHeight: 22 },
  walletAction: { minHeight: 48, alignSelf: 'flex-start', justifyContent: 'center', marginTop: 4, paddingHorizontal: 16, paddingVertical: 12, borderRadius: 14, backgroundColor: palette.primary },
  walletActionText: { color: palette.onPrimary, fontSize: 14, fontWeight: '800' },
  nextStep: { gap: 5, padding: 18, borderRadius: world.radius.card, backgroundColor: world.card },
  nextStepLabel: { color: palette.primary, fontSize: 12, fontWeight: '900' },
  nextStepText: { color: world.cardMuted, fontSize: 13, lineHeight: 20 },
  stateWrap: { padding: 20, paddingTop: 16 },
} satisfies Record<string, ImageStyle | TextStyle | ViewStyle>;
}
