import type { ImageStyle, TextStyle, ViewStyle } from 'react-native';
import type { AppColors } from '../../theme/palette';
import type { WorldTheme } from '../../theme/world';

export function makeMerchantDetailStyles(palette: AppColors, world: WorldTheme, hairlineWidth = 1) {
  return {
  // No background: the sky page shows through between the cards.
  content: { gap: 16, paddingHorizontal: 20 },
  hero: { gap: 10, padding: 22, borderRadius: world.radius.card, backgroundColor: world.card },
  heroTopline: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  heroEyebrow: { color: palette.primary, fontSize: 12, fontWeight: '900', letterSpacing: 1.1 },
  demoBadge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: world.radius.chip, backgroundColor: palette.primaryContainer, color: palette.onPrimaryContainer, fontSize: 12, fontWeight: '900' },
  title: { color: world.cardInk, fontSize: 30, fontWeight: '900', lineHeight: 38, letterSpacing: -0.6 },
  story: { color: world.cardMuted, fontSize: 16, lineHeight: 25 },
  inlineError: { padding: 12, borderRadius: 12, backgroundColor: palette.errorContainer },
  inlineErrorText: { color: palette.onErrorContainer, fontSize: 13, lineHeight: 19 },
  infoCard: { paddingHorizontal: 18, paddingVertical: 6, borderRadius: world.radius.card, backgroundColor: world.card },
  infoRow: { flexDirection: 'row', gap: 18, paddingVertical: 16, borderBottomWidth: hairlineWidth, borderBottomColor: palette.separator },
  infoRowStacked: { flexDirection: 'column', gap: 6 },
  infoLabel: { width: 72, color: world.cardMuted, fontSize: 13, fontWeight: '700' },
  infoLabelStacked: { width: undefined },
  infoValue: { flex: 1, color: world.cardInk, fontSize: 14, fontWeight: '700', textAlign: 'right' },
  infoValueStacked: { flex: undefined, textAlign: 'left' },
  directionsAction: { minHeight: 48, alignSelf: 'flex-start', justifyContent: 'center', marginBottom: 8, paddingHorizontal: 16, borderRadius: 12, backgroundColor: palette.primary },
  directionsText: { color: palette.onPrimary, fontSize: 14, fontWeight: '800' },
  directionsNotice: { color: world.cardMuted, fontSize: 14, lineHeight: 21, paddingBottom: 12 },
  sectionEyebrow: { color: palette.primary, fontSize: 13, fontWeight: '900' },
  menuHeading: { marginTop: 12 },
  feedbackCard: { gap: 12, padding: 18, borderRadius: world.radius.card, backgroundColor: world.card },
  feedbackHeading: { color: world.cardInk, fontSize: 18, fontWeight: '900' },
  feedbackTags: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  feedbackTag: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: world.radius.chip, backgroundColor: palette.primaryContainer },
  feedbackTagText: { color: palette.onPrimaryContainer, fontSize: 13, fontWeight: '700' },
  feedbackEmpty: { color: world.cardMuted, fontSize: 13, lineHeight: 20 },
  feedbackAction: { minHeight: 48, alignSelf: 'flex-start', justifyContent: 'center', paddingHorizontal: 16, borderRadius: 12, backgroundColor: palette.primary },
  feedbackActionText: { color: palette.onPrimary, fontSize: 14, fontWeight: '800' },
  feedbackMessage: { color: world.cardInk, fontSize: 13, lineHeight: 20 },
  campaignTitle: { color: world.cardInk, fontSize: 18, fontWeight: '800' },
  period: { color: world.cardMuted, fontSize: 13 },
  rewardCard: { gap: 8, padding: 20, borderRadius: world.radius.card, backgroundColor: world.card },
  rewardHeading: { color: world.cardInk, fontSize: 18, fontWeight: '900' },
  previewList: { gap: 10, marginTop: 8 },
  previewRow: { flexDirection: 'row', alignItems: 'center', gap: 14, minHeight: 76 },
  previewArt: { width: 72, height: 72, alignItems: 'center', justifyContent: 'center' },
  previewImage: { width: 72, height: 72 },
  previewCopy: { flex: 1, gap: 4 },
  previewLabel: { color: world.cardInk, fontSize: 16, fontWeight: '800' },
  previewState: { color: palette.primary, fontSize: 14, fontWeight: '700' },
  fallbackGoal: { color: world.cardInk, fontSize: 15, fontWeight: '700', paddingVertical: 6 },
  previewRetry: { minHeight: 48, justifyContent: 'center' },
  previewRetryText: { color: palette.primary, fontSize: 14, fontWeight: '700', textDecorationLine: 'underline' },
  progressLine: { color: palette.primary, fontSize: 14, fontWeight: '800', lineHeight: 21, marginTop: 6 },
  boundaryCard: { gap: 5, padding: 14, borderRadius: world.radius.card, backgroundColor: palette.primaryContainer },
  boundaryTitle: { color: palette.onPrimaryContainer, fontSize: 14, fontWeight: '800' },
  boundaryBody: { color: palette.onPrimaryContainer, fontSize: 13, lineHeight: 20 },
  walletLink: { minHeight: 48, alignSelf: 'flex-start', justifyContent: 'center' },
  walletLinkText: { color: palette.onPrimaryContainer, fontSize: 14, fontWeight: '800', textDecorationLine: 'underline' },
  walletAction: { minHeight: 48, alignSelf: 'flex-start', justifyContent: 'center', marginTop: 4, paddingHorizontal: 16, paddingVertical: 12, borderRadius: 14, backgroundColor: palette.primary },
  walletActionText: { color: palette.onPrimary, fontSize: 14, fontWeight: '800' },
  nextStep: { gap: 5, padding: 18, borderRadius: world.radius.card, backgroundColor: world.card },
  nextStepLabel: { color: palette.primary, fontSize: 12, fontWeight: '900' },
  nextStepText: { color: world.cardMuted, fontSize: 13, lineHeight: 20 },
  stateWrap: { padding: 20, paddingTop: 16 },
} satisfies Record<string, ImageStyle | TextStyle | ViewStyle>;
}
