import type { ImageStyle, TextStyle, ViewStyle } from 'react-native';
import type { AppColors } from '../../theme/palette';
import { uiMetrics } from '../../theme/ui-metrics';

export function makeCollectionStyles(palette: AppColors, hairlineWidth = 1) {
  return {
  centered: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12, padding: 28, backgroundColor: palette.background },
  centeredTitle: { color: palette.label, fontSize: 21, fontWeight: '900', textAlign: 'center' },
  centeredBody: { color: palette.secondaryLabel, fontSize: 14, lineHeight: 22, textAlign: 'center' },
  primaryButton: { minHeight: uiMetrics.minTouch, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18, paddingVertical: 12, borderRadius: 14, backgroundColor: palette.primary },
  primaryButtonText: { color: palette.onPrimary, fontSize: 14, fontWeight: '900', textAlign: 'center' },
  content: { gap: uiMetrics.sectionGap, padding: uiMetrics.pageInset, paddingBottom: 48, backgroundColor: palette.background },
  inlineError: { padding: 12, borderRadius: 12, color: palette.onErrorContainer, backgroundColor: palette.errorContainer, fontSize: 13 },
  inlineMessage: { padding: 12, borderRadius: 12, color: palette.onPrimaryContainer, backgroundColor: palette.primaryContainer, fontSize: 13, lineHeight: 20 },
  recoveryBanner: { gap: 10, padding: 14, borderRadius: 14, backgroundColor: palette.errorContainer },
  recoveryText: { color: palette.onErrorContainer, fontSize: 13, lineHeight: 20 },
  recoveryButton: { minHeight: uiMetrics.minTouch, maxWidth: '100%', alignSelf: 'flex-start', justifyContent: 'center', paddingHorizontal: 13, paddingVertical: 9, borderRadius: 12, backgroundColor: palette.surface },
  recoveryButtonText: { color: palette.primary, fontSize: 12, fontWeight: '900' },
  section: { gap: 5 },
  sectionTitle: { color: palette.label, fontSize: 22, fontWeight: '900' },
  subsectionTitle: { marginTop: 8, color: palette.label, fontSize: 17, fontWeight: '800' },
  sectionNote: { color: palette.secondaryLabel, fontSize: 13, lineHeight: 20 },
  sectionBody: { gap: 12, marginTop: 9 },
  stampGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  stampSlot: { alignItems: 'center', gap: 5, paddingTop: 14, paddingBottom: 12, paddingHorizontal: 8, borderRadius: 18 },
  stampInk: { alignItems: 'center', justifyContent: 'center', width: 64, height: 64, marginBottom: 4, padding: 3, borderWidth: 2, borderRadius: 32 },
  stampInkEmpty: { borderStyle: 'dashed' },
  stampImage: { width: 54, height: 54, borderRadius: 27 },
  stampImageEmpty: { opacity: 0.4 },
  stampMystery: { position: 'absolute', fontSize: 24, fontWeight: '900' },
  stampName: { fontSize: 13, fontWeight: '800', lineHeight: 18, textAlign: 'center' },
  stampStatus: { fontSize: 11, lineHeight: 16, textAlign: 'center' },
  collectibleCard: { gap: 9, padding: 18, borderRadius: 20, backgroundColor: palette.surface },
  collectibleArt: { borderRadius: 16 } as ImageStyle,
  collectibleArtNote: { color: palette.secondaryLabel, fontSize: 11, lineHeight: 16 } as TextStyle,
  collectibleTopline: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  goalBadge: { color: palette.primary, fontSize: 12, fontWeight: '900' },
  appStatus: { color: palette.onSuccessContainer, fontSize: 11, fontWeight: '900' },
  itemTitle: { color: palette.label, fontSize: 19, fontWeight: '900' },
  itemMeta: { color: palette.secondaryLabel, fontSize: 12, lineHeight: 18 },
  nftRow: { flexDirection: 'row', justifyContent: 'space-between', paddingTop: 9, borderTopWidth: hairlineWidth, borderTopColor: palette.separator },
  nftLabel: { color: palette.secondaryLabel, fontSize: 12, fontWeight: '700' },
  nftValue: { color: palette.label, fontSize: 12, fontWeight: '900' },
  recipient: { color: palette.secondaryLabel, fontFamily: 'monospace', fontSize: 11 },
  nftIdentity: { color: palette.primary, fontFamily: 'monospace', fontSize: 11, lineHeight: 17 },
  mintButton: { minHeight: uiMetrics.minTouch, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 14, borderRadius: 14, backgroundColor: palette.primary },
  mintButtonText: { color: palette.onPrimary, fontSize: 13, fontWeight: '900', textAlign: 'center' },
  walletButton: { minHeight: uiMetrics.minTouch, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 14, borderRadius: 14, borderWidth: 1, borderColor: palette.primary },
  walletButtonText: { color: palette.primary, fontSize: 13, fontWeight: '900', textAlign: 'center' },
  disabled: { opacity: 0.42 },
  visitRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 14, padding: 16, borderRadius: 18, backgroundColor: palette.surface },
  visitMerchant: { color: palette.label, fontSize: 16, fontWeight: '900' },
  visitLeft: { flex: 1, minWidth: 0 },
  visitRight: { alignItems: 'flex-end', gap: 3, flexShrink: 0 },
  visitDate: { color: palette.label, fontSize: 13, fontWeight: '800' },
  progressLabel: { color: palette.primary, fontSize: 11, fontWeight: '800' },
  emptyCopy: { padding: 18, borderRadius: 18, color: palette.secondaryLabel, backgroundColor: palette.surface, fontSize: 14, lineHeight: 22 },
  } satisfies Record<string, ImageStyle | TextStyle | ViewStyle>;
}
