import type { AppColors } from '@/theme/palette';
import type { WorldTheme } from '@/theme/world';

export function makeRealMapStyles(palette:AppColors,world:WorldTheme) {return ({
  screen:{flex:1,backgroundColor:world.page},header:{paddingHorizontal:20,paddingTop:4,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},title:{fontSize:25,fontWeight:'800',color:world.skyInk},
  content:{padding:20,gap:12},mapCanvas:{flex:1,minHeight:120},mapPanel:{maxHeight:220,minHeight:80,flexShrink:1},actions:{flexDirection:'row',flexWrap:'wrap',gap:8,alignItems:'center',paddingVertical:3},button:{minHeight:48,maxWidth:'100%',paddingHorizontal:14,paddingVertical:10,borderRadius:14,borderWidth:1,borderColor:palette.separator,backgroundColor:palette.primaryContainer,justifyContent:'center'},selected:{borderColor:palette.primary},buttonText:{fontSize:14,fontWeight:'700',color:palette.onPrimaryContainer},input:{minHeight:48,margin:0,paddingHorizontal:14,paddingVertical:10,fontSize:16,borderRadius:14,borderWidth:1.5,borderColor:world.cardMuted,color:world.cardInk,backgroundColor:world.card},
  searchInput:{marginHorizontal:20,marginVertical:8},filters:{flexGrow:0,flexShrink:0},filterRow:{flexWrap:'nowrap',paddingHorizontal:20,paddingBottom:8},
  largeMapControls:{maxHeight:'45%',flexGrow:0,flexShrink:1},
  row:{minHeight:86,flexDirection:'row',gap:12,padding:12,borderRadius:16,backgroundColor:world.card,marginVertical:4},photoBox:{width:72,height:72,backgroundColor:world.paper,borderRadius:10,justifyContent:'center',alignItems:'center',overflow:'hidden'},photo:{width:72,height:72},photoPlaceholder:{fontSize:11,color:world.paperInk,textAlign:'center'},name:{fontSize:16,fontWeight:'700',color:world.cardInk},muted:{fontSize:13,color:world.cardMuted,lineHeight:19},heading:{fontSize:18,fontWeight:'800',color:world.skyInk},notice:{fontSize:14,color:palette.onErrorContainer,padding:8,backgroundColor:palette.errorContainer,borderRadius:10},panel:{padding:12,borderRadius:16,backgroundColor:world.card,gap:8},courseStop:{paddingVertical:8,borderTopWidth:1,borderColor:palette.separator,gap:4},
}) as const;}
