import type { ImageStyle, TextStyle, ViewStyle } from 'react-native';
import type { AppColors } from '../../theme/palette';
import { uiMetrics } from '../../theme/ui-metrics';

export function makeMerchantListStyles(palette: AppColors, hairlineWidth = 1) {
  return {
  content: {
    flexGrow: 1,
    padding: uiMetrics.pageInset,
    paddingBottom: 48,
    backgroundColor: palette.background,
  },
  header: { gap: 6, marginBottom: 8 },
  banner: { width: '100%', aspectRatio: 2.6, borderRadius: uiMetrics.cardRadius, backgroundColor: palette.surface },
  discoveryTools: { gap: 12, paddingTop: 4 },
  searchField: { minHeight: 52, flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 14, borderRadius: 16, borderWidth: 1 },
  searchGlyph: { justifyContent: 'center' },
  searchInput: { flex: 1, minWidth: 0, fontSize: 15, paddingVertical: 10 },
  clearSearch: { minHeight: uiMetrics.minTouch, justifyContent: 'center', paddingHorizontal: 4 },
  clearSearchText: { fontSize: 13, fontWeight: '700' },
  filters: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  filterChip: { minHeight: uiMetrics.minTouch, justifyContent: 'center', paddingHorizontal: 16, borderRadius: 999, borderWidth: 1 },
  filterText: { fontSize: 13, fontWeight: '800' },
  title: { color: palette.label, fontSize: 25, fontWeight: '800', lineHeight: 33, letterSpacing: -0.5 },
  intro: { color: palette.secondaryLabel, fontSize: 14, lineHeight: 20 },
  recommendationAction: { minHeight: uiMetrics.minTouch, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 10 },
  recommendationActionText: { color: palette.primary, fontSize: 13, fontWeight: '800' },
  sectionHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 8, marginTop: 8 },
  sectionTitleRow: { flexDirection: 'row', alignItems: 'baseline', gap: 8 },
  sectionEyebrow: { color: palette.label, fontSize: 18, fontWeight: '800' },
  sectionCount: { color: palette.secondaryLabel, fontSize: 13, fontWeight: '700' },
  inlineError: { padding: 12, borderRadius: 12, backgroundColor: palette.errorContainer },
  inlineErrorText: { color: palette.onErrorContainer, fontSize: 13, lineHeight: 19 },
  separator: { height: 14 },
  card: {
    gap: 10,
    padding: 16,
    borderRadius: uiMetrics.cardRadius,
    borderCurve: 'continuous',
    borderWidth: hairlineWidth,
    borderColor: palette.separator,
    backgroundColor: palette.surface,
  },
  cardPressed: { opacity: 0.72, transform: [{ scale: 0.99 }] },
  cardTopline: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  routeNumber: { marginRight: 'auto', color: palette.primary, fontSize: 13, fontWeight: '900', letterSpacing: 1.2 },
  statusBadge: { paddingHorizontal: 9, paddingVertical: 5, borderRadius: 999, backgroundColor: palette.successContainer },
  statusBadgeText: { color: palette.onSuccessContainer, fontSize: 11, fontWeight: '800' },
  fullBadge: { backgroundColor: palette.errorContainer },
  fullBadgeText: { color: palette.onErrorContainer },
  demoBadge: { paddingHorizontal: 8, paddingVertical: 5, borderRadius: 999, backgroundColor: palette.primaryContainer },
  demoBadgeText: { color: palette.onPrimaryContainer, fontSize: 10, fontWeight: '900', letterSpacing: 0.6 },
  cardNameRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  cardTitle: { color: palette.label, fontSize: 21, fontWeight: '800', letterSpacing: -0.4 },
  cardStory: { color: palette.secondaryLabel, fontSize: 14, lineHeight: 21 },
  cardRule: { height: hairlineWidth, backgroundColor: palette.separator },
  cardMeta: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  cardAddress: { flex: 1, color: palette.label, fontSize: 13, fontWeight: '600' },
  cardArrow: { color: palette.primary, fontSize: 20, fontWeight: '800' },
  campaignName: { color: palette.secondaryLabel, fontSize: 12 },
  statusPanel: { alignItems: 'center', gap: 12, padding: 28, borderRadius: 22, backgroundColor: palette.surface },
  emptyState: { gap: 14, padding: 24, borderRadius: 24, borderCurve: 'continuous' },
  emptyRoute: { height: 24, flexDirection: 'row', alignItems: 'center' },
  routeStop: { width: 15, height: 15, borderRadius: 999 },
  routeStopOutline: { backgroundColor: 'transparent', borderWidth: 2 },
  routeTrack: { width: 72, height: 1, borderTopWidth: 1, borderStyle: 'dashed' },
  emptyEyebrow: { fontSize: 12, fontWeight: '900', letterSpacing: 0.3 },
  emptyTitle: { fontSize: 24, lineHeight: 31, fontWeight: '900', letterSpacing: -0.5 },
  emptyBody: { fontSize: 14, lineHeight: 22 },
  journey: { gap: 7, paddingTop: 14, borderTopWidth: 1 },
  journeyLabel: { fontSize: 12, fontWeight: '900' },
  journeyText: { fontSize: 13, lineHeight: 21, fontWeight: '700' },
  emptyRefresh: { minHeight: uiMetrics.minTouch, alignSelf: 'flex-start', justifyContent: 'center', paddingHorizontal: 18, borderRadius: 14 },
  emptyRefreshText: { fontSize: 14, fontWeight: '800' },
  statusTitle: { color: palette.label, fontSize: 20, fontWeight: '800', textAlign: 'center' },
  statusBody: { color: palette.secondaryLabel, fontSize: 15, lineHeight: 23, textAlign: 'center' },
  primaryAction: { marginTop: 4, paddingHorizontal: 18, paddingVertical: 12, borderRadius: 14, backgroundColor: palette.primary },
  primaryActionText: { color: palette.onPrimary, fontSize: 14, fontWeight: '800' },
  footer: { marginTop: 22, color: palette.secondaryLabel, fontSize: 12, lineHeight: 19 },
  configurationContent: { flex: 1, justifyContent: 'center', gap: 18, padding: 24, backgroundColor: palette.background },
  configurationCard: { gap: 8, padding: 18, borderRadius: 18, backgroundColor: palette.surface },
  configurationCode: { color: palette.primary, fontFamily: 'monospace', fontSize: 14, fontWeight: '700' },
  configurationHelp: { color: palette.secondaryLabel, fontSize: 13, lineHeight: 20 },
  } satisfies Record<string, ImageStyle | TextStyle | ViewStyle>;
}
