import type { ImageStyle, TextStyle, ViewStyle } from 'react-native';

import type { MedalColors } from '../theme/medal-colors';
import type { AppColors } from '../theme/palette';
import { uiMetrics } from '../theme/ui-metrics';

// 탐험 여권 화면 조각의 스타일. 화면별 조합은 여기서만 고치면 되도록 한 곳에 모았다.
export function makeGamificationStyles(palette: AppColors, medal: MedalColors) {
  return {
    // Shared
    button: { minHeight: uiMetrics.minTouch, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18, paddingVertical: 12, borderRadius: 16, backgroundColor: palette.primary },
    buttonText: { color: palette.onPrimary, fontSize: 15, fontWeight: '800', textAlign: 'center' },
    secondaryButton: { minHeight: uiMetrics.minTouch, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18, paddingVertical: 12, borderRadius: 16, backgroundColor: palette.primaryContainer },
    secondaryButtonText: { color: palette.onPrimaryContainer, fontSize: 15, fontWeight: '800', textAlign: 'center' },
    ghostButton: { minHeight: uiMetrics.minTouch, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18, paddingVertical: 10, borderRadius: 16 },
    ghostButtonText: { color: palette.primary, fontSize: 15, fontWeight: '800', textAlign: 'center' },
    pressed: { opacity: 0.72, transform: [{ scale: 0.98 }] },
    disabled: { opacity: 0.45 },
    closeButton: { width: uiMetrics.minTouch, height: uiMetrics.minTouch, alignItems: 'center', justifyContent: 'center', borderRadius: 24 },
    chip: { flexDirection: 'row', alignItems: 'center', alignSelf: 'flex-start', gap: 6, minHeight: 28, paddingHorizontal: 10, paddingVertical: 4, borderRadius: 14 },
    chipText: { fontSize: 12, fontWeight: '800', lineHeight: 17, flexShrink: 1 },
    errorText: { padding: 12, borderRadius: 14, color: palette.onErrorContainer, backgroundColor: palette.errorContainer, fontSize: 13, lineHeight: 20 },

    // Passport hero
    passport: { overflow: 'hidden', gap: 16, padding: 20, borderRadius: 24 },
    passportEyebrowRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
    passportEyebrow: { color: medal.skyMuted, fontSize: 12, fontWeight: '800', letterSpacing: 0.6 },
    passportMain: { flexDirection: 'row', alignItems: 'center', gap: 16 },
    passportMainStacked: { flexDirection: 'column', alignItems: 'flex-start' },
    passportStampFrame: { padding: 4, borderRadius: 48, backgroundColor: '#FFFFFF', transform: [{ rotate: '-6deg' }], shadowColor: '#0B2A5B', shadowOpacity: 0.18, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, elevation: 4 },
    passportStamp: { width: 84, height: 84, borderRadius: 42 } as ImageStyle,
    passportCopy: { flex: 1, minWidth: 0, gap: 4 },
    passportRank: { color: medal.skyInk, fontSize: 26, fontWeight: '800', lineHeight: 32, letterSpacing: -0.4 },
    passportBadgeCount: { color: medal.skyInk, fontSize: 15, fontWeight: '700', lineHeight: 21 },
    passportBadgeNumber: { color: palette.primary, fontWeight: '900', fontVariant: ['tabular-nums'] },
    pipRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', rowGap: 8 },
    pipGroup: { flexDirection: 'row', alignItems: 'center', gap: 5, marginRight: 8 },
    pip: { width: 16, height: 16, borderRadius: 8, borderWidth: 2 },
    passportNext: { color: medal.skyMuted, fontSize: 14, fontWeight: '700', lineHeight: 20 },
    passportCta: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 10, paddingVertical: 10, paddingLeft: 14, paddingRight: 10, borderRadius: 18, borderWidth: 2, borderColor: palette.primary },
    passportCtaText: { flex: 1, minWidth: 140, color: palette.label, fontSize: 15, fontWeight: '800', lineHeight: 21 },
    passportCtaButton: { minHeight: uiMetrics.minTouch, minWidth: 72, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18, borderRadius: 14, backgroundColor: palette.primary },
    countStrip: { flexDirection: 'row', gap: 8 },
    countStripStacked: { flexDirection: 'column' },
    countPill: { flex: 1, minWidth: 0, gap: 1, paddingVertical: 9, paddingHorizontal: 10, borderRadius: 16 },
    countPillStacked: { flexDirection: 'row', alignItems: 'baseline', gap: 8 },
    countValue: { color: medal.skyInk, fontSize: 20, fontWeight: '900', fontVariant: ['tabular-nums'] },
    countLabel: { color: medal.skyMuted, fontSize: 12, fontWeight: '700' },
    demoNote: { alignSelf: 'flex-start', paddingHorizontal: 10, paddingVertical: 5, borderRadius: 12, overflow: 'hidden', color: palette.onAccentContainer, backgroundColor: palette.accentContainer, fontSize: 12, fontWeight: '800', lineHeight: 17 },

    // Medal shelf
    shelf: { flexDirection: 'row', gap: 10 },
    shelfStacked: { flexDirection: 'column' },
    medalCard: { flex: 1, alignItems: 'center', gap: 7, paddingTop: 14, paddingBottom: 14, paddingHorizontal: 4, borderRadius: uiMetrics.cardRadius, backgroundColor: palette.surface },
    medalCardStacked: { flexDirection: 'row', alignItems: 'center', gap: 14, paddingHorizontal: 16, paddingVertical: 14 },
    medalCardCopy: { alignItems: 'center', gap: 5, minWidth: 0 },
    medalCardCopyStacked: { flex: 1, alignItems: 'flex-start' },
    medalName: { color: palette.label, fontSize: 14, fontWeight: '800', lineHeight: 19, textAlign: 'center', letterSpacing: -0.3 },
    medalNameStacked: { textAlign: 'left' },
    medalProgress: { color: palette.secondaryLabel, fontSize: 12, fontWeight: '600', lineHeight: 17, textAlign: 'center' },
    medalProgressStacked: { textAlign: 'left' },
    shelfSkeleton: { flex: 1, height: 176, borderRadius: uiMetrics.cardRadius, backgroundColor: palette.surface },
    retryCard: { gap: 12, padding: 18, borderRadius: uiMetrics.cardRadius, backgroundColor: palette.surface },
    retryText: { color: palette.label, fontSize: 14, lineHeight: 21 },

    // Detail sheet & bottom sheets
    backdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(8, 14, 28, 0.55)' },
    sheet: { paddingTop: 8, borderTopLeftRadius: 28, borderTopRightRadius: 28, backgroundColor: palette.background },
    sheetScroll: { flexGrow: 0, flexShrink: 1 },
    sheetHandle: { alignSelf: 'center', width: 40, height: 5, borderRadius: 3, backgroundColor: palette.separator },
    sheetHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingLeft: uiMetrics.pageInset, paddingRight: 8 },
    sheetTitle: { flex: 1, color: palette.label, fontSize: 18, fontWeight: '800', lineHeight: 24 },
    sheetBody: { gap: 18, paddingHorizontal: uiMetrics.pageInset, paddingTop: 4 },
    detailHero: { alignItems: 'center', gap: 10 },
    detailTitle: { color: palette.label, fontSize: 24, fontWeight: '800', lineHeight: 31, textAlign: 'center', letterSpacing: -0.3 },
    detailMeasure: { color: palette.secondaryLabel, fontSize: 15, lineHeight: 22, textAlign: 'center' },
    progressTrack: { height: 10, overflow: 'hidden', borderRadius: 5, backgroundColor: palette.primaryContainer },
    progressFill: { height: '100%', borderRadius: 5, backgroundColor: palette.primary },
    progressCaption: { color: palette.label, fontSize: 14, fontWeight: '700', lineHeight: 20 },
    tierTable: { overflow: 'hidden', borderRadius: 18, backgroundColor: palette.surface },
    tierRow: { flexDirection: 'row', alignItems: 'center', gap: 12, minHeight: 56, paddingHorizontal: 14, paddingVertical: 10 },
    tierRowCurrent: { backgroundColor: palette.primaryContainer },
    tierDot: { width: 30, height: 30, alignItems: 'center', justifyContent: 'center', borderRadius: 15, borderWidth: 2 },
    tierDotText: { fontSize: 12, fontWeight: '900' },
    tierRowCopy: { flex: 1, minWidth: 0, gap: 1 },
    tierRowName: { color: palette.label, fontSize: 15, fontWeight: '800' },
    tierRowRule: { color: palette.secondaryLabel, fontSize: 13, lineHeight: 18 },
    tierRowStatus: { color: palette.secondaryLabel, fontSize: 13, fontWeight: '800', textAlign: 'right' },
    tierRowStatusDone: { color: palette.success },
    ruleNote: { color: palette.secondaryLabel, fontSize: 13, lineHeight: 20 },
    sheetActions: { gap: 10, paddingTop: 4 },

    // Reward track
    trackPanel: { gap: 16, padding: 18, borderRadius: uiMetrics.cardRadius, backgroundColor: palette.surface },
    trackHeader: { flexDirection: 'row', alignItems: 'baseline', justifyContent: 'space-between', gap: 8, flexWrap: 'wrap' },
    trackLabel: { color: palette.label, fontSize: 15, fontWeight: '800' },
    trackSummary: { color: palette.primary, fontSize: 13, fontWeight: '800' },
    trackValue: { color: palette.primary, fontSize: 15, fontWeight: '900', fontVariant: ['tabular-nums'] },
    rail: { height: 12, justifyContent: 'center' },
    railTrack: { height: 8, overflow: 'hidden', borderRadius: 4, backgroundColor: palette.primaryContainer },
    railFill: { height: '100%', borderRadius: 4, backgroundColor: palette.primary },
    railMarker: { position: 'absolute', width: 12, height: 12, marginLeft: -6, borderRadius: 6, borderWidth: 2 },
    boxList: { gap: 10 },
    boxRowCard: { flexDirection: 'row', alignItems: 'center', gap: 14, paddingVertical: 12, paddingLeft: 10, paddingRight: 14, borderRadius: 18, borderWidth: 2, borderColor: 'transparent', backgroundColor: palette.background },
    boxRowCardReady: { borderColor: palette.primary, backgroundColor: palette.primaryContainer },
    boxRowBody: { flex: 1, minWidth: 0, gap: 8 },
    boxRowCopy: { gap: 6, alignItems: 'flex-start' },
    boxRowTitleLine: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'baseline', columnGap: 8 },
    boxName: { color: palette.label, fontSize: 16, fontWeight: '800', lineHeight: 22 },
    boxRequirement: { color: palette.secondaryLabel, fontSize: 12, fontWeight: '700' },
    boxOffer: { color: palette.secondaryLabel, fontSize: 13, lineHeight: 18 },
    boxButton: { alignSelf: 'flex-start', minHeight: uiMetrics.minTouch, minWidth: 128, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 20, borderRadius: 14, backgroundColor: palette.primary },
    boxButtonText: { color: palette.onPrimary, fontSize: 15, fontWeight: '900', textAlign: 'center' },
    boxError: { color: palette.error, fontSize: 13, lineHeight: 18 },

    // Coupons
    couponList: { gap: 14 },
    ticket: { overflow: 'visible' },
    ticketTop: { gap: 5, paddingHorizontal: 20, paddingTop: 18, paddingBottom: 16 },
    ticketBottom: { gap: 12, paddingHorizontal: 20, paddingTop: 14, paddingBottom: 18 },
    ticketEyebrow: { color: palette.onAccentContainer, fontSize: 12, fontWeight: '800', opacity: 0.85 },
    ticketTitle: { color: palette.onAccentContainer, fontSize: 19, fontWeight: '900', lineHeight: 25 },
    ticketMerchant: { color: palette.onAccentContainer, fontSize: 14, fontWeight: '700', lineHeight: 20 },
    ticketDetail: { color: palette.onAccentContainer, fontSize: 13, lineHeight: 19 },
    ticketMetaRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 8 },
    ticketExpiry: { color: palette.onAccentContainer, fontSize: 13, fontWeight: '800', fontVariant: ['tabular-nums'] },
    /** Right column kept free for the "사용 완료" stamp so it never covers text. */
    ticketStampRoom: { paddingRight: 124 },
    inkStamp: { position: 'absolute', top: '50%', marginTop: -50, right: 16, alignItems: 'center', justifyContent: 'center', padding: 3, borderWidth: 3, borderRadius: 999, borderColor: medal.stampInk },
    inkStampInner: { alignItems: 'center', justifyContent: 'center', width: 88, height: 88, paddingHorizontal: 6, borderWidth: 1.5, borderRadius: 999, borderColor: medal.stampInk },
    inkStampText: { color: medal.stampInk, fontSize: 15, fontWeight: '900', letterSpacing: 0.5, lineHeight: 19, textAlign: 'center' },
    emptyCoupons: { padding: 16, borderRadius: 18, color: palette.secondaryLabel, backgroundColor: palette.surface, fontSize: 14, lineHeight: 21 },

    // Coupon use sheet
    qrCard: { alignItems: 'center', gap: 10, padding: 18, borderRadius: 22, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: palette.separator },
    qrCode: { color: '#192331', fontSize: 24, fontWeight: '900', letterSpacing: 2, fontVariant: ['tabular-nums'] },
    qrCodeLabel: { color: '#58677D', fontSize: 12, fontWeight: '800' },
    qrTimer: { color: '#2456D6', fontSize: 14, fontWeight: '800', fontVariant: ['tabular-nums'] },
    qrHint: { color: palette.label, fontSize: 14, lineHeight: 21, textAlign: 'center' },
    qrPlaceholder: { alignItems: 'center', justifyContent: 'center', gap: 10 },
    couponSummary: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 14, borderRadius: 18, backgroundColor: palette.accentContainer },
    couponSummaryCopy: { flex: 1, minWidth: 0, gap: 2 },
    showcaseLine: { color: palette.secondaryLabel, fontSize: 12, lineHeight: 18, textAlign: 'center' },
    redeemedPanel: { alignItems: 'center', gap: 12, paddingVertical: 18 },
    redeemedTitle: { color: palette.label, fontSize: 24, fontWeight: '900', textAlign: 'center' },
    redeemedBody: { color: palette.secondaryLabel, fontSize: 15, lineHeight: 22, textAlign: 'center' },
    bigInkStamp: { alignItems: 'center', justifyContent: 'center', padding: 5, borderWidth: 4, borderRadius: 999, borderColor: medal.stampInk },
    bigInkStampInner: { alignItems: 'center', justifyContent: 'center', width: 132, height: 132, borderWidth: 2, borderRadius: 66, borderColor: medal.stampInk },
    bigInkStampText: { color: medal.stampInk, fontSize: 24, fontWeight: '900', letterSpacing: 1.5, textAlign: 'center' },

    // Reveal & celebration
    fullScreen: { flex: 1 },
    celebrationScroll: { flexGrow: 1, alignItems: 'center', justifyContent: 'center', gap: 14, paddingHorizontal: 24, paddingBottom: 32 },
    celebrationClose: { position: 'absolute', right: 8, zIndex: 2 },
    stage: { width: 220, height: 220, alignItems: 'center', justifyContent: 'center' },
    stagePaper: { position: 'absolute', width: 184, height: 184, borderRadius: 92, borderWidth: 2, borderStyle: 'dashed', borderColor: palette.primary, backgroundColor: palette.background },
    inkBlot: { position: 'absolute', width: 170, height: 170, borderRadius: 85, backgroundColor: palette.primary },
    inkRing: { position: 'absolute', width: 170, height: 170, borderRadius: 85, borderWidth: 3, borderColor: palette.primary },
    stampImage: { width: 150, height: 150, borderRadius: 75 } as ImageStyle,
    celebrationTitle: { color: medal.skyInk, fontSize: 28, fontWeight: '900', lineHeight: 36, textAlign: 'center', letterSpacing: -0.5 },
    celebrationBody: { color: medal.skyMuted, fontSize: 16, lineHeight: 24, textAlign: 'center' },
    chipColumn: { alignSelf: 'stretch', alignItems: 'center', gap: 8 },
    celebrationChip: { flexDirection: 'row', alignItems: 'center', gap: 8, minHeight: 40, maxWidth: '100%', paddingHorizontal: 14, paddingVertical: 8, borderRadius: 20 },
    celebrationChipText: { flexShrink: 1, fontSize: 14, fontWeight: '800', lineHeight: 20 },
    celebrationActions: { alignSelf: 'stretch', gap: 10, marginTop: 6 },
    revealStage: { width: 200, height: 170, alignItems: 'center', justifyContent: 'center' },
    revealTitle: { color: palette.label, fontSize: 24, fontWeight: '900', lineHeight: 31, textAlign: 'center' },
    revealBody: { color: palette.secondaryLabel, fontSize: 15, lineHeight: 22, textAlign: 'center' },
    revealCard: { alignSelf: 'stretch', gap: 16, marginHorizontal: 16, padding: 20, borderRadius: 28, backgroundColor: palette.background },
    revealCenter: { flex: 1, justifyContent: 'center', paddingVertical: 24 },
  } satisfies Record<string, ImageStyle | TextStyle | ViewStyle>;
}

export type GamificationStyles = ReturnType<typeof makeGamificationStyles>;
